---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
taxonomies:
  # category: "categories"
  Tags: "tags"
  Series: "series"
baseurl: "http://arnavk.com/"
title: "Arnav Khare"
canonifyurls: true
theme: "hugo_theme_beg"
...
